#include "Langue.h"
#include "UiScale.h"
#include <cstdlib>

namespace vsm::app::ui {

namespace {

// ---------------------------------------------------------------------------
// LA TABLE ANGLAISE. Clé = le français EXACT tel qu'il arrive à `tr()`.
//
// ELLE EST ÉCRITE À LA MAIN, ET C'EST VOULU. Une traduction automatique d'un
// logiciel de musique se trompe précisément là où cela compte : « piste » est
// *track*, « la piste » d'un magnétophone ; « prise » est *take* et non *plug* ;
// « écoute » est *monitoring* et non *listening* ; « départ » est *send*. Ces
// mots ont un sens fixé par le métier, et c'est ce sens-là qu'un musicien
// cherche dans un menu.
//
// CE QUI NE SE TRADUIT PAS, ET POURQUOI. Les sérigraphies des façades
// (« CUTOFF », « BASS DRUM ») imitent des machines réelles : les traduire dans
// un sens ou dans l'autre ferait mentir la réplique. Les noms de fichiers et de
// clés de préférences (« project.json ») ne sont pas du texte, ce sont des
// identifiants. Ils traversent la table inchangés, volontairement.
// ---------------------------------------------------------------------------
struct Paire { const char* fr; const char* en; };

const Paire kAnglais[] = {
    { "    ↳ ",
      "    ↳ " },
    { "    ↳ une reconstruction est déjà en cours",
      "    ↳ a reconstruction is already running" },
    { "  (celle qu'on entend)",
      "  (the one you hear)" },
    { "  (introuvable)",
      "  (not found)" },
    { " (Ctrl+S)",
      " (Ctrl+S)" },
    { " : aucune piste n'y est routée",
      ": no track is routed to it" },
    { " autres sorties sur des pistes",
      " other outputs onto tracks" },
    { " auxiliaire",
      " auxiliary" },
    { " caractères)",
      " characters)" },
    { " fois",
      " times" },
    { " fois)",
      " times)" },
    { " inserts)",
      " inserts)" },
    { " inserts, remplace)",
      " inserts, replaces)" },
    { " masquées)",
      " hidden)" },
    { " ms (",
      " ms (" },
    { " pistes)",
      " tracks)" },
    { " points)",
      " points)" },
    { " prises)",
      " takes)" },
    { " réserve à l'ouverture",
      " reservation on opening" },
    { " réserves à l'ouverture",
      " reservations on opening" },
    { " sections)",
      " sections)" },
    { " thread",
      " thread" },
    { " threads auxiliaires ici)",
      " auxiliary threads here)" },
    { " visibles)...",
      " visible)..." },
    { " échantillons)",
      " samples)" },
    { " événements)",
      " events)" },
    { " — bus de groupe",
      " — group bus" },
    { "(Aucun)",
      "(None)" },
    { "(aucun preset dans ",
      "(no preset in " },
    { "(aucun — les tranches n'ont pas de bouton de départ)",
      "(none — the strips have no send button)" },
    { "(aucun)",
      "(none)" },
    { "(aucune : la machine interne seulement)",
      "(none: the internal machine only)" },
    { "(cette machine n'en a qu'une)",
      "(this machine has only one)" },
    { "(en boucle et en mode empilé, chaque passage ",
      "(when looping in stacked mode, each pass " },
    { "(en boucle et en mode empilé, chaque passage devient une prise)",
      "(when looping in stacked mode, each pass becomes a take)" },
    { "+ Ajouter\nune piste",
      "+ Add\na track" },
    { "+ Ajouter une piste",
      "+ Add a track" },
    { ", banque ",
      ", bank " },
    { "1 mesure",
      "1 bar" },
    { "2 mesures",
      "2 bars" },
    { "Accord",
      "Chord" },
    { "Active",
      "Active" },
    { "Affichage",
      "View" },
    { "Afficher toutes les pistes (",
      "Show all tracks (" },
    { "Afficher toutes les pistes (aucune masquée)",
      "Show all tracks (none hidden)" },
    { "Aide",
      "Help" },
    { "Aimant",
      "Snap" },
    { "Ajouter : ",
      "Add: " },
    { "Ajouter la chaîne (rien de copié)",
      "Append the chain (nothing copied)" },
    { "Ajouter la chaîne à la suite (",
      "Append the chain (" },
    { "Ajouter un bus de départ",
      "Add a send bus" },
    { "Ajouter un groupe",
      "Add a group" },
    { "Ajouter une piste MIDI",
      "Add a MIDI track" },
    { "Ajouter une piste audio",
      "Add an audio track" },
    { "Aller à la mesure… (Maj+P, double-clic sur la position)",
      "Go to bar… (Shift+P, double-click the position)" },
    { "Analyseur de spectre...",
      "Spectrum analyser..." },
    { "Annuler",
      "Undo" },
    { "Appliquer le groove (aucun en mémoire)",
      "Apply the groove (none in memory)" },
    { "Appliquer le groove « ",
      "Apply the groove « " },
    { "Appliquer un preset de piste (les notes et les clips restent)",
      "Apply a track preset (notes and clips stay)" },
    { "Arrangement",
      "Arrangement" },
    { "Assembler les prises... (",
      "Comp the takes... (" },
    { "Assembler les prises... (aucune)",
      "Comp the takes... (none)" },
    { "Associations MIDI (",
      "MIDI mappings (" },
    { "Aucun",
      "None" },
    { "Auto",
      "Auto" },
    { "Automation",
      "Automation" },
    { "Automatique (",
      "Automatic (" },
    { "Balayage des plugins en cours...",
      "Plugin scan in progress..." },
    { "Basculer l'écoute A/B (touche R)",
      "Toggle A/B monitoring (R key)" },
    { "Bus",
      "Bus" },
    { "Bus de départ",
      "Send bus" },
    { "Canal ",
      "Channel " },
    { "Canal d'entrée MIDI (",
      "MIDI input channel (" },
    { "Canal d'entrée MIDI (tous)",
      "MIDI input channel (all)" },
    { "Carré (une période par mesure)",
      "Square (one cycle per bar)" },
    { "Ce que fait la prise MIDI",
      "What MIDI recording does" },
    { "Charger l'original (référence A/B)...",
      "Load the original (A/B reference)..." },
    { "Charger un groove…",
      "Load a groove…" },
    { "Charger un instrument VST3 sur la piste...",
      "Load a VST3 instrument onto the track..." },
    { "Charger un plugin CLAP sur la piste...",
      "Load a CLAP plugin onto the track..." },
    { "Clavier d'ordinateur (A S D F… jouent la piste choisie, Z/X : octave)",
      "Computer keyboard (A S D F… play the selected track, Z/X: octave)" },
    { "Clic",
      "Click" },
    { "Coll.",
      "Glue" },
    { "Coller la chaîne (",
      "Paste the chain (" },
    { "Coller la chaîne (rien de copié)",
      "Paste the chain (nothing copied)" },
    { "Copier",
      "Copy" },
    { "Copier la chaîne d'inserts (",
      "Copy the insert chain (" },
    { "Coup.",
      "Cut" },
    { "Couper toutes les notes (panic)",
      "All notes off (panic)" },
    { "Créer un clip d'une mesure à la tête de lecture",
      "Create a one-bar clip at the playhead" },
    { "Depart vers ",
      "Send to " },
    { "Descendre la piste",
      "Move the track down" },
    { "Dess.",
      "Draw" },
    { "Dessiner l'automation sur la sélection",
      "Draw automation over the selection" },
    { "Droit",
      "Straight" },
    { "Dupliquer la piste sélectionnée",
      "Duplicate the selected track" },
    { "Décompte",
      "Count-in" },
    { "Découper la sélection aux transitoires (clips audio)",
      "Split the selection at transients (audio clips)" },
    { "Dégeler la piste (l'instrument reprend)",
      "Unfreeze the track (the instrument resumes)" },
    { "Désactiver la piste (sa machine et ses inserts sont libérés)",
      "Disable the track (its machine and inserts are released)" },
    { "Déverrouiller la piste (le montage reprend)",
      "Unlock the track (editing resumes)" },
    { "Eff.",
      "Erase" },
    { "Effets",
      "Effects" },
    { "Effets MIDI de la piste (",
      "MIDI effects of the track (" },
    { "Empiler les prises",
      "Stack takes" },
    { "Enregistrement",
      "Recording" },
    { "Enregistrer",
      "Save" },
    { "Enregistrer comme modèle de projet",
      "Save as project template" },
    { "Enregistrer la piste comme preset…",
      "Save the track as a preset…" },
    { "Enregistrer le groove…",
      "Save the groove…" },
    { "Enregistrer sous...",
      "Save as..." },
    { "Entrer dans le dossier du dessus",
      "Enter the folder above" },
    { "Exporter MIDI...",
      "Export MIDI..." },
    { "Exporter audio (WAV)...",
      "Export audio (WAV)..." },
    { "Exporter la piste choisie en MIDI (choisir une piste MIDI)...",
      "Export the selected track as MIDI (select a MIDI track)..." },
    { "Exporter la piste choisie en MIDI (« ",
      "Export the selected track as MIDI (« " },
    { "Exporter les stems (un WAV par piste)...",
      "Export stems (one WAV per track)..." },
    { "Extraire le groove de la piste choisie",
      "Extract the groove from the selected track" },
    { "Fantômes",
      "Ghosts" },
    { "Fenêtre unique",
      "Single window" },
    { "Fermer",
      "Close" },
    { "Fichier",
      "File" },
    { "Filtrer les pistes...",
      "Filter tracks..." },
    { "Forme des fondus croisés",
      "Crossfade shape" },
    { "Gamme",
      "Scale" },
    { "Geler la piste (l'instrument s'arrête)",
      "Freeze the track (the instrument stops)" },
    { "Grande (112 px)",
      "Large (112 px)" },
    { "Grille",
      "Grid" },
    { "Groupe ",
      "Group " },
    { "Groupe d'édition (couper et déplacer ensemble)",
      "Edit group (cut and move together)" },
    { "Hauteur des pistes",
      "Track height" },
    { "Historique des modifications...",
      "Edit history..." },
    { "Humaniser",
      "Humanise" },
    { "Importer un MIDI dans le projet...",
      "Import a MIDI file into the project..." },
    { "Importer un fichier audio sur une piste neuve...",
      "Import an audio file onto a new track..." },
    { "Importer un projet (Ableton, FL Studio, Cubase)...",
      "Import a project (Ableton, FL Studio, Cubase)..." },
    { "Indiquer le dossier de la chaîne...",
      "Set the analysis chain folder..." },
    { "Instrument parmi les plugins trouves...",
      "Instrument from the plugins found..." },
    { "Insérer du silence entre les locateurs (Ctrl+Maj+I)",
      "Insert silence between the locators (Ctrl+Shift+I)" },
    { "Jamais mesurée — les prises audio ne sont ",
      "Never measured — audio takes are " },
    { "Jamais mesurée — les prises audio ne sont pas compensées",
      "Never measured — audio takes are not compensated" },
    { "Jusqu'à la fin de la boucle (",
      "To the end of the loop (" },
    { "Jusqu'à la fin de la boucle (rien n'y tient, ou pas de boucle)",
      "To the end of the loop (nothing fits, or no loop)" },
    { "L'effacer",
      "Clear it" },
    { "La prendre sur la boucle",
      "Take it over the loop" },
    { "Langue",
      "Language" },
    { "Latence d'entrée",
      "Input latency" },
    { "Legato",
      "Legato" },
    { "Lente",
      "Slow" },
    { "Linéaire (deux copies du même son)",
      "Linear (two copies of the same sound)" },
    { "Liste",
      "List" },
    { "Locateurs sur la sélection (P)",
      "Locators around the selection (P)" },
    { "MASTER",
      "MASTER" },
    { "MONO",
      "MONO" },
    { "Masquer la piste (elle continue de sonner)",
      "Hide the track (it keeps sounding)" },
    { "Mesurer (brancher la sortie sur l'entrée)...",
      "Measure it (patch the output into the input)..." },
    { "Mesures",
      "Bars" },
    { "Mesurée : ",
      "Measured: " },
    { "Minutes:secondes",
      "Minutes:seconds" },
    { "Mixage",
      "Mixing" },
    { "Mixer",
      "Mixer" },
    { "Mono-cœur (aucun thread auxiliaire)",
      "Single core (no auxiliary thread)" },
    { "Monter la piste",
      "Move the track up" },
    { "Muet",
      "Mute" },
    { "Navigateur",
      "Browser" },
    { "Ne plus protéger cette piste du solo des autres (Alt+clic sur Solo)",
      "Stop shielding this track from other tracks' solo (Alt+click Solo)" },
    { "Normale (56 px)",
      "Normal (56 px)" },
    { "Note :",
      "Note:" },
    { "Notes du projet... (",
      "Project notes... (" },
    { "Notes du projet... (vides)",
      "Project notes... (empty)" },
    { "Nouveau depuis le modèle",
      "New from template" },
    { "Nouveau projet",
      "New project" },
    { "Ordre de jeu... (",
      "Play order... (" },
    { "Ordre de jeu... (aucune section)",
      "Play order... (no section)" },
    { "Oublier la mesure",
      "Forget the measurement" },
    { "Ouvrir MIDI...",
      "Open MIDI..." },
    { "Ouvrir l'interface du plugin de la piste",
      "Open the track plugin's window" },
    { "Ouvrir un projet VSM...",
      "Open a VSM project..." },
    { "Pas à pas",
      "Step" },
    { "Petite (24 px)",
      "Small (24 px)" },
    { "Piano Roll",
      "Piano Roll" },
    { "Piste",
      "Track" },
    { "Pistes",
      "Tracks" },
    { "Plein écran (F11)",
      "Full screen (F11)" },
    { "Plus aucun solo (Ctrl+clic sur Solo)",
      "No solo at all (Ctrl+click Solo)" },
    { "Plus...",
      "More..." },
    { "Pointé",
      "Dotted" },
    { "Post-fader (le fader l'emporte avec lui)",
      "Post-fader (the fader carries it along)" },
    { "Prise ",
      "Take " },
    { "Prises de « ",
      "Takes of « " },
    { "Programme MIDI (",
      "MIDI program (" },
    { "Programme MIDI (aucun)...",
      "MIDI program (none)..." },
    { "Projet ouvert, avec des réserves",
      "Project opened, with reservations" },
    { "Projets récents",
      "Recent projects" },
    { "Protéger cette piste du solo des autres (Alt+clic sur Solo)",
      "Shield this track from other tracks' solo (Alt+click Solo)" },
    { "Pré-fader (le fader ne l'affecte pas)",
      "Pre-fader (the fader does not affect it)" },
    { "Préférences...",
      "Preferences..." },
    { "Publier les ",
      "Publish the " },
    { "Publier les sorties de l'instrument ",
      "Publish the outputs of instrument " },
    { "Publier les sorties de l'instrument (cette machine n'en a qu'une)",
      "Publish the instrument's outputs (this machine has only one)" },
    { "Puissance constante (deux prises différentes)",
      "Constant power (two different takes)" },
    { "Quantifier",
      "Quantise" },
    { "Quantifier la dernière prise (grille du piano roll)",
      "Quantise the last take (piano roll grid)" },
    { "Quitter",
      "Quit" },
    { "Raccourcis clavier...",
      "Keyboard shortcuts..." },
    { "Rampe descendante",
      "Ramp down" },
    { "Rampe montante",
      "Ramp up" },
    { "Ranger cette piste dans un dossier neuf",
      "Move this track into a new folder" },
    { "Rapide",
      "Fast" },
    { "Rechercher les plugins installes...",
      "Scan for installed plugins..." },
    { "Reconstruire en visant la parité des pistes (le défaut de la chaîne)",
      "Reconstruct aiming for track parity (the chain's default)" },
    { "Reconstruire un morceau...",
      "Reconstruct a song..." },
    { "Remplacer",
      "Replace" },
    { "Rendu muet par son dossier",
      "Muted by its folder" },
    { "Renommer les pistes en série (",
      "Rename tracks in series (" },
    { "Replier",
      "Collapse" },
    { "Reporter la piste en audio (définitif)",
      "Bounce the track to audio (permanent)" },
    { "Reporter la sélection en audio (sur une piste neuve)",
      "Bounce the selection to audio (onto a new track)" },
    { "Reporter les effets MIDI dans les notes (définitif)",
      "Bounce the MIDI effects into the notes (permanent)" },
    { "Retirer ce bus",
      "Remove this bus" },
    { "Retirer le changement de cette mesure",
      "Remove the change at this bar" },
    { "Retirer le changement de cette mesure (aucun ici)",
      "Remove the change at this bar (none here)" },
    { "Retirer tous les effets MIDI",
      "Remove all MIDI effects" },
    { "Retirer une prise du tiroir",
      "Remove a take from the drawer" },
    { "Retour audible",
      "Audible return" },
    { "Règle",
      "Ruler" },
    { "Réactiver la piste (sa machine revient)",
      "Re-enable the track (its machine comes back)" },
    { "Récupérer ce qui vient d'être joué (",
      "Recover what was just played (" },
    { "Récupérer ce qui vient d'être joué (rien en mémoire)",
      "Recover what was just played (nothing in memory)" },
    { "Réduire les points d'automation (",
      "Thin automation points (" },
    { "Région de punch (Alt sur la règle)",
      "Punch region (Alt on the ruler)" },
    { "Réglages audio...",
      "Audio settings..." },
    { "Répéter la sélection (à la suite)",
      "Repeat the selection (end to end)" },
    { "Rétablir",
      "Redo" },
    { "SANS SON",
      "NO SOUND" },
    { "Signature à la tête de lecture",
      "Time signature at the playhead" },
    { "Sinus (une période par mesure)",
      "Sine (one cycle per bar)" },
    { "Solo exclusif de la piste choisie (Ctrl+clic sur Solo)",
      "Exclusive solo of the selected track (Ctrl+click Solo)" },
    { "Sortie MIDI matérielle",
      "Hardware MIDI output" },
    { "Sortie MIDI matérielle (→ ",
      "Hardware MIDI output (→ " },
    { "Sortir du dossier",
      "Leave the folder" },
    { "Statistiques du projet...",
      "Project statistics..." },
    { "Suivre",
      "Follow" },
    { "Superposer",
      "Overlay" },
    { "Supprimer",
      "Delete" },
    { "Supprimer la piste sélectionnée",
      "Delete the selected track" },
    { "Supprimer le temps entre les locateurs (Ctrl+Maj+K)",
      "Delete time between the locators (Ctrl+Shift+K)" },
    { "Swing",
      "Swing" },
    { "Synth Rack",
      "Synth Rack" },
    { "Sél.",
      "Sel." },
    { "Taille de l'interface",
      "Interface size" },
    { "Tempo",
      "Tempo" },
    { "Threads de rendu",
      "Render threads" },
    { "Tous les canaux",
      "All channels" },
    { "Tout",
      "Fit" },
    { "Tout sélectionner dans l'arrangement (Ctrl+A)",
      "Select all in the arrangement (Ctrl+A)" },
    { "Toutes les pistes à la fenêtre (arrangement)",
      "Fit all tracks to the window (arrangement)" },
    { "Transcrire le clip audio choisi en MIDI (",
      "Transcribe the selected audio clip to MIDI (" },
    { "Transcrire le clip audio choisi en MIDI (Basic Pitch)",
      "Transcribe the selected audio clip to MIDI (Basic Pitch)" },
    { "Triangle (une période par mesure)",
      "Triangle (one cycle per bar)" },
    { "Trim ",
      "Trim " },
    { "Triolet",
      "Triplet" },
    { "Verrouiller la piste (le montage s'arrête)",
      "Lock the track (editing stops)" },
    { "Voir le dernier rapport d'import",
      "Show the last import report" },
    { "Voir le rapport de reconstruction",
      "Show the reconstruction report" },
    { "Vél.",
      "Vel." },
    { "W latch",
      "W latch" },
    { "W touch",
      "W touch" },
    { "bus de groupe",
      "group bus" },
    { "devient une prise)",
      "becomes a take)" },
    { "dossier (ne joue rien)",
      "folder (plays nothing)" },
    { "pas compensées",
      "not compensated" },
    { "project.json",
      "project.json" },
    { "reconstruireEnParite",
      "reconstruireEnParite" },
    { "À propos de Vintage Synth MIDI Studio",
      "About Vintage Synth MIDI Studio" },
    { "Éclater par hauteur (",
      "Split by pitch (" },
    { "Éclater par hauteur (une seule hauteur ici)",
      "Split by pitch (only one pitch here)" },
    { "Écoute : les deux",
      "Monitoring: both" },
    { "Écoute : original",
      "Monitoring: original" },
    { "Écoute : reconstruction",
      "Monitoring: reconstruction" },
    { "Écoute A/B : pas d'original",
      "A/B monitoring: no original" },
    { "Écoute automatique (une piste audio armée, transport arrêté ou en enregistrement)",
      "Automatic monitoring (one audio track armed, transport stopped or recording)" },
    { "Écoute de l'entrée",
      "Input monitoring" },
    { "Écoute en mono (jamais dans un export)",
      "Mono monitoring (never in an export)" },
    { "Écoute manuelle (l'interrupteur ci-dessus)",
      "Manual monitoring (the switch above)" },
    { "Écoute quand une piste est armée (une piste audio armée, toujours)",
      "Monitoring while a track is armed (one audio track armed, always)" },
    { "Écouter l'entrée en direct (latence du périphérique)",
      "Monitor the input live (device latency)" },
    { "Édition",
      "Edit" },
};

constexpr int kNombreDePaires = static_cast<int>(sizeof(kAnglais) / sizeof(kAnglais[0]));

Langue::Choix& etatCourant() {
    static Langue::Choix courant = Langue::Choix::Francais;
    return courant;
}

const char* kCleReglage = "langueInterface";

Langue::Choix depuisLeTexte(const juce::String& texte, Langue::Choix defaut) {
    const juce::String t = texte.trim().toLowerCase();
    if (t == "en" || t == "anglais" || t == "english") return Langue::Choix::Anglais;
    if (t == "fr" || t == "francais" || t == juce::String::fromUTF8("français")) return Langue::Choix::Francais;
    return defaut;
}

/// Installe (ou retire) la table de JUCE. Le français ne pose AUCUNE table :
/// `juce::translate` rend alors son argument, ce qui est exactement le
/// comportement voulu et ne coûte pas une recherche.
void poserLaTable(Langue::Choix choix) {
    if (choix == Langue::Choix::Francais) {
        juce::LocalisedStrings::setCurrentMappings(nullptr);
        return;
    }
    juce::String texte;
    texte << "language: English\n" << "countries: gb us\n\n";
    for (const auto& paire : kAnglais) {
        // LE FORMAT DE JUCE, ET SON SEUL PIÈGE : la clé et la valeur sont des
        // littéraux entre guillemets sur une ligne, et un guillemet ou un
        // retour à la ligne DANS le texte doit être échappé -- sans quoi la
        // ligne se coupe en silence et la traduction disparaît sans erreur.
        auto echappe = [](const char* brut) {
            return juce::String::fromUTF8(brut).replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n");
        };
        texte << "\"" << echappe(paire.fr) << "\" = \"" << echappe(paire.en) << "\"\n";
    }
    juce::LocalisedStrings::setCurrentMappings(new juce::LocalisedStrings(texte, false));
}

} // namespace

Langue::Choix Langue::courante() { return etatCourant(); }

int Langue::tailleDeLaTable() { return kNombreDePaires; }

juce::String Langue::libelle(Choix choix) {
    // CHAQUE LANGUE DANS LA SIENNE : c'est la convention de tous les sélecteurs
    // de langue, et la seule qui permette à quelqu'un de retrouver la sienne
    // quand l'interface est posée dans une langue qu'il ne lit pas.
    return choix == Choix::Anglais ? juce::String("English")
                                   : juce::String::fromUTF8("Français");
}

bool Langue::appliquer(Choix choix) {
    const bool change = choix != etatCourant();
    etatCourant() = choix;
    poserLaTable(choix);
    UiScale::properties().setValue(kCleReglage, choix == Choix::Anglais ? "en" : "fr");
    UiScale::properties().saveIfNeeded();
    return change;
}

void Langue::appliquerAuDemarrage() {
    Choix choix = depuisLeTexte(UiScale::properties().getValue(kCleReglage, "fr"),
                                Choix::Francais);
    // VSM_LANGUE L'EMPORTE, SANS ÉCRASER LE RÉGLAGE. Un banc choisit sa langue
    // pour une course ; il ne doit pas changer ce que l'utilisateur a réglé,
    // sans quoi une vérification en anglais laisserait le DAW en anglais.
    if (const char* force = std::getenv("VSM_LANGUE"); force != nullptr && *force) {
        etatCourant() = depuisLeTexte(juce::String::fromUTF8(force), choix);
        poserLaTable(etatCourant());
        return;
    }
    etatCourant() = choix;
    poserLaTable(choix);
}

juce::String tr(const char* texte) {
    // `fromUTF8` ET NON `juce::String(const char*)` : le second lit les octets
    // en Latin-1 et rend « s'éclaircit » en « s'Â©claircit ». Passer par la
    // traduction devient donc aussi la façon sûre d'écrire un accent.
    return juce::translate(juce::String::fromUTF8(texte));
}

juce::String tr(const char8_t* texte) {
    return juce::translate(juce::String::fromUTF8(reinterpret_cast<const char*>(texte)));
}

juce::String tr(const juce::String& texte) { return juce::translate(texte); }

} // namespace vsm::app::ui
