#include "Langue.h"
#include "UiScale.h"
#include <cstdlib>

namespace vsm::app::ui {

namespace {

// ---------------------------------------------------------------------------
// LA TABLE ANGLAISE. Clé = le français EXACT tel qu'il arrive à `tr()`.
//
// ELLE EST ÉCRITE À LA MAIN, ET C'EST VOULU. Une traduction automatique d'un
// logiciel de musique se trompe précisément là où cela compte : « piste » est
// *track*, « la piste » d'un magnétophone ; « prise » est *take* et non *plug* ;
// « écoute » est *monitoring* et non *listening* ; « départ » est *send*. Ces
// mots ont un sens fixé par le métier, et c'est ce sens-là qu'un musicien
// cherche dans un menu.
//
// CE QUI NE SE TRADUIT PAS, ET POURQUOI. Les sérigraphies des façades
// (« CUTOFF », « BASS DRUM ») imitent des machines réelles : les traduire dans
// un sens ou dans l'autre ferait mentir la réplique. Les noms de fichiers et de
// clés de préférences (« project.json ») ne sont pas du texte, ce sont des
// identifiants. Ils traversent la table inchangés, volontairement.
// ---------------------------------------------------------------------------
struct Paire { const char* fr; const char* en; };

const Paire kAnglais[] = {
    { "    ↳ ",
      "    ↳ " },
    { "    ↳ une reconstruction est déjà en cours",
      "    ↳ a reconstruction is already running" },
    { "  (celle qu'on entend)",
      "  (the one you hear)" },
    { "  (introuvable)",
      "  (not found)" },
    { " (Ctrl+S)",
      " (Ctrl+S)" },
    { " : aucune piste n'y est routée",
      ": no track is routed to it" },
    { " autres sorties sur des pistes",
      " other outputs onto tracks" },
    { " auxiliaire",
      " auxiliary" },
    { " caractères)",
      " characters)" },
    { " fois",
      " times" },
    { " fois)",
      " times)" },
    { " inserts)",
      " inserts)" },
    { " inserts, remplace)",
      " inserts, replaces)" },
    { " masquées)",
      " hidden)" },
    { " ms (",
      " ms (" },
    { " pistes)",
      " tracks)" },
    { " points)",
      " points)" },
    { " prises)",
      " takes)" },
    { " réserve à l'ouverture",
      " reservation on opening" },
    { " réserves à l'ouverture",
      " reservations on opening" },
    { " sections)",
      " sections)" },
    { " sur ",
      " on " },
    { " thread",
      " thread" },
    { " threads auxiliaires ici)",
      " auxiliary threads here)" },
    { " visibles)...",
      " visible)..." },
    { " échantillons)",
      " samples)" },
    { " événements)",
      " events)" },
    { " — bus de groupe",
      " — group bus" },
    { " — paramètres",
      " — parameters" },
    { "%1  (celle qu'on entend)",
      "%1  (the one you hear)" },
    { "%1 demi-ton",
      "%1 semitone" },
    { "%1 demi-tons",
      "%1 semitones" },
    { "%1 fois",
      "%1 times" },
    { "%1 thread(s)",
      "%1 thread(s)" },
    { "(Aucun)",
      "(None)" },
    { "(aucun preset dans ",
      "(no preset in " },
    { "(aucun preset de ce type dans la bibliothèque ni le projet)",
      "(no preset of this type in the library or the project)" },
    { "(aucun — les tranches n'ont pas de bouton de départ)",
      "(none — the strips have no send button)" },
    { "(aucun)",
      "(none)" },
    { "(aucune : la machine interne seulement)",
      "(none: the internal machine only)" },
    { "(cette machine n'en a qu'une)",
      "(this machine has only one)" },
    { "(désactivé)",
      "(disabled)" },
    { "(en boucle et en mode empilé, chaque passage ",
      "(when looping in stacked mode, each pass " },
    { "(en boucle et en mode empilé, chaque passage devient une prise)",
      "(when looping in stacked mode, each pass becomes a take)" },
    { "+ Ajouter\nune piste",
      "+ Add\na track" },
    { "+ Ajouter une piste",
      "+ Add a track" },
    { ", banque ",
      ", bank " },
    { "0 (remettre)",
      "0 (reset)" },
    { "0 dB (remettre)",
      "0 dB (reset)" },
    { "1 mesure",
      "1 bar" },
    { "2 mesures",
      "2 bars" },
    { "Accord",
      "Chord" },
    { "Actif / contourné (Bypass) : l'effet tourne encore et garde sa latence",
      "Active / bypassed: the effect keeps running and keeps its latency" },
    { "Actif / contourné : contourné, l'effet ne transforme plus rien, et les notes passent telles qu'elles sont écrites.",
      "Active / bypassed: when bypassed, the effect no longer changes anything, and the notes pass as they are written." },
    { "Active",
      "Active" },
    { "Adopter le tempo du clip",
      "Adopt the clip's tempo" },
    { "Affichage",
      "View" },
    { "Afficher toutes les pistes",
      "Show all tracks" },
    { "Afficher toutes les pistes (",
      "Show all tracks (" },
    { "Afficher toutes les pistes (%1 masquées)",
      "Show all tracks (%1 hidden)" },
    { "Afficher toutes les pistes (aucune masquée)",
      "Show all tracks (none hidden)" },
    { "Aide",
      "Help" },
    { "Aimant",
      "Snap" },
    { "Aimantation",
      "Snap" },
    { "Ajouter :",
      "Add:" },
    { "Ajouter : ",
      "Add: " },
    { "Ajouter : %1",
      "Add: %1" },
    { "Ajouter la chaîne (rien de copié)",
      "Append the chain (nothing copied)" },
    { "Ajouter la chaîne d'inserts",
      "Append the insert chain" },
    { "Ajouter la chaîne à la suite (",
      "Append the chain (" },
    { "Ajouter la chaîne à la suite (%1 inserts)",
      "Append the chain after (%1 inserts)" },
    { "Ajouter le tronçon",
      "Add the segment" },
    { "Ajouter un bus de départ",
      "Add a send bus" },
    { "Ajouter un effet",
      "Add an effect" },
    { "Ajouter un effet MIDI",
      "Add a MIDI effect" },
    { "Ajouter un groupe",
      "Add a group" },
    { "Ajouter un marqueur de tempo",
      "Add a warp marker" },
    { "Ajouter un marqueur ici",
      "Add a warp marker here" },
    { "Ajouter un preset d'effet",
      "Add an effect preset" },
    { "Ajouter une piste",
      "Add a track" },
    { "Ajouter une piste MIDI",
      "Add a MIDI track" },
    { "Ajouter une piste audio",
      "Add an audio track" },
    { "Ajouter ▸",
      "Add ▸" },
    { "Ajuster à la fenêtre",
      "Fit to the window" },
    { "Aller à la fin du morceau",
      "Go to the end of the song" },
    { "Aller à la mesure…",
      "Go to bar…" },
    { "Aller à la mesure… (Maj+P, double-clic sur la position)",
      "Go to bar… (Shift+P, double-click the position)" },
    { "Aléatoire (±20)",
      "Random (±20)" },
    { "Analyseur de spectre...",
      "Spectrum analyser..." },
    { "Annuler",
      "Undo" },
    { "Annuler : ",
      "Undo: " },
    { "Aplatir (écrit le matériau)",
      "Flatten (writes the material)" },
    { "Aplatir l'ordre de jeu",
      "Flatten the play order" },
    { "Appliquer le groove",
      "Apply the groove" },
    { "Appliquer le groove (aucun en mémoire)",
      "Apply the groove (none in memory)" },
    { "Appliquer le groove « ",
      "Apply the groove « " },
    { "Appliquer le groove « %1 »",
      "Apply the groove “%1”" },
    { "Appliquer un preset",
      "Apply a preset" },
    { "Appliquer un preset de piste",
      "Apply a track preset" },
    { "Appliquer un preset de piste (les notes et les clips restent)",
      "Apply a track preset (notes and clips stay)" },
    { "Apprendre...",
      "Learn..." },
    { "Appuyez sur la nouvelle touche pour « %1 » (Échap : annuler)",
      "Press the new key for “%1” (Esc: cancel)" },
    { "Arpèges",
      "Arpeggios" },
    { "Arpéger : aller-retour",
      "Arpeggiate: up and down" },
    { "Arpéger : aléatoire",
      "Arpeggiate: random" },
    { "Arpéger : descendant",
      "Arpeggiate: down" },
    { "Arpéger : montant",
      "Arpeggiate: up" },
    { "Arpégiateur",
      "Arpeggiator" },
    { "Arrangement",
      "Arrangement" },
    { "Assembler les prises",
      "Comp takes" },
    { "Assembler les prises... (",
      "Comp the takes... (" },
    { "Assembler les prises... (%1 prises)",
      "Comp takes... (%1 takes)" },
    { "Assembler les prises... (aucune)",
      "Comp the takes... (none)" },
    { "Associations MIDI (",
      "MIDI mappings (" },
    { "Associations MIDI (%1)",
      "MIDI mappings (%1)" },
    { "Associations MIDI (%1)...",
      "MIDI mappings (%1)..." },
    { "Aucun",
      "None" },
    { "Aucune association.\n\nDans le Synth Rack, clic droit sur un réglage ▸ « Apprendre un contrôleur MIDI », puis tournez le potentiomètre.",
      "No mappings.\n\nIn the Synth Rack, right-click a control ▸ “Learn a MIDI controller”, then turn the knob." },
    { "Aucune section : posez des repères sur la règle. Une section va d'un repère au suivant.",
      "No sections: place markers on the ruler. A section runs from one marker to the next." },
    { "Aucune — seul le projet ouvert est indexé",
      "None — only the open project is indexed" },
    { "Audio",
      "Audio" },
    { "Augmenté",
      "Augmented" },
    { "Auto",
      "Auto" },
    { "Automation",
      "Automation" },
    { "Automatique",
      "Automatic" },
    { "Automatique (",
      "Automatic (" },
    { "Automatique (%1 ici)",
      "Automatic (%1 here)" },
    { "Balayage des plugins en cours...",
      "Plugin scan in progress..." },
    { "Basculer l'écoute A/B",
      "Toggle A/B monitoring" },
    { "Basculer l'écoute A/B (touche R)",
      "Toggle A/B monitoring (R key)" },
    { "Bibliothèque (navigateur)",
      "Library (browser)" },
    { "Boucle (marche / arrêt)",
      "Loop (on / off)" },
    { "Bus",
      "Bus" },
    { "Bus de départ",
      "Send bus" },
    { "Caler un marqueur de tempo",
      "Place a warp marker" },
    { "Canal ",
      "Channel " },
    { "Canal MIDI",
      "MIDI channel" },
    { "Canal d'entrée MIDI",
      "MIDI input channel" },
    { "Canal d'entrée MIDI (",
      "MIDI input channel (" },
    { "Canal d'entrée MIDI (tous)",
      "MIDI input channel (all)" },
    { "Carré (une période par mesure)",
      "Square (one cycle per bar)" },
    { "Ce morceau a plusieurs tempos ou signatures. Aplatir déplace le matériau et LAISSE la carte de tempo en place : un ralenti joué deux fois ne suivra pas sa section.",
      "This song has several tempos or time signatures. Flattening moves the material and LEAVES the tempo map in place: a slowdown played twice will not follow its section." },
    { "Ce que fait la prise MIDI",
      "What MIDI recording does" },
    { "Cette piste n'a aucune prise conservée. Enregistrez en mode « empiler » pour en garder plusieurs.",
      "This track has no kept takes. Record in “stack” mode to keep several." },
    { "Changer de machine",
      "Change machine" },
    { "Charger l'original (référence A/B)...",
      "Load the original (A/B reference)..." },
    { "Charger un groove…",
      "Load a groove…" },
    { "Charger un instrument",
      "Load an instrument" },
    { "Charger un instrument VST3",
      "Load a VST3 instrument" },
    { "Charger un instrument VST3 sur la piste...",
      "Load a VST3 instrument onto the track..." },
    { "Charger un plugin CLAP",
      "Load a CLAP plugin" },
    { "Charger un plugin CLAP sur la piste...",
      "Load a CLAP plugin onto the track..." },
    { "Charger un preset d'effet",
      "Load an effect preset" },
    { "Chaîne d'analyse",
      "Analysis chain" },
    { "Chercher une machine, un preset, un échantillon...",
      "Search for a machine, a preset, a sample..." },
    { "Choisir le dossier...",
      "Choose the folder..." },
    { "Choisir toutes les pistes",
      "Select all tracks" },
    { "Choisir une prise",
      "Choose a take" },
    { "Chromatique",
      "Chromatic" },
    { "Ciseaux",
      "Scissors" },
    { "Clavier d'ordinateur (A S D F… jouent la piste choisie, Z/X : octave)",
      "Computer keyboard (A S D F… play the selected track, Z/X: octave)" },
    { "Clic",
      "Click" },
    { "Clip à l'envers",
      "Reverse a clip" },
    { "Coll.",
      "Glue" },
    { "Colle",
      "Glue" },
    { "Coller",
      "Paste" },
    { "Coller des clips",
      "Paste clips" },
    { "Coller la chaîne (",
      "Paste the chain (" },
    { "Coller la chaîne (%1 inserts, remplace)",
      "Paste the chain (%1 inserts, replaces)" },
    { "Coller la chaîne (rien de copié)",
      "Paste the chain (nothing copied)" },
    { "Coller la chaîne d'inserts",
      "Paste the insert chain" },
    { "Coller à la tête de lecture",
      "Paste at the playhead" },
    { "Commandes",
      "Commands" },
    { "Composer (écrit le matériau)",
      "Compose (writes the material)" },
    { "Contenir entre 20 et 100",
      "Keep between 20 and 100" },
    { "Contourner tous les effets",
      "Bypass all effects" },
    { "Contourner tout",
      "Bypass all" },
    { "Contourner un effet",
      "Bypass an effect" },
    { "Contourner un effet MIDI",
      "Bypass a MIDI effect" },
    { "Contourné : le signal passe sec, retardé de la latence de l'effet",
      "Bypassed: the signal passes dry, delayed by the effect's latency" },
    { "Contraindre à la gamme",
      "Constrain to scale" },
    { "Convertir en copie indépendante",
      "Convert to an independent copy" },
    { "Copie indépendante",
      "Independent copy" },
    { "Copier",
      "Copy" },
    { "Copier la chaîne d'inserts (",
      "Copy the insert chain (" },
    { "Copier la chaîne d'inserts (%1)",
      "Copy the insert chain (%1)" },
    { "Couleur d'un clip",
      "Clip colour" },
    { "Couleur d'une piste",
      "Track colour" },
    { "Couleur de la piste",
      "Use the track colour" },
    { "Couleur…",
      "Colour…" },
    { "Coup.",
      "Cut" },
    { "Couper",
      "Cut" },
    { "Couper toutes les notes (panic)",
      "All notes off (panic)" },
    { "Couper un clip",
      "Split a clip" },
    { "Couper à la tête de lecture",
      "Split at the playhead" },
    { "Couper à la tête de lecture (Ctrl+E)",
      "Split at the playhead (Ctrl+E)" },
    { "Courber un segment d'automation",
      "Curve an automation segment" },
    { "Crayon",
      "Pencil" },
    { "Créer un clip",
      "Create a clip" },
    { "Créer un clip d'une mesure à la tête de lecture",
      "Create a one-bar clip at the playhead" },
    { "Depart vers ",
      "Send to " },
    { "Descendre",
      "Move down" },
    { "Descendre la piste",
      "Move the track down" },
    { "Dess.",
      "Draw" },
    { "Dessiner l'automation sur la sélection",
      "Draw automation over the selection" },
    { "Dessiner une automation",
      "Draw automation" },
    { "Deux fois plus lent (départs et durées ×2)",
      "Half speed (starts and lengths ×2)" },
    { "Deux fois plus vite (départs et durées ÷2)",
      "Double speed (starts and lengths ÷2)" },
    { "Diminué",
      "Diminished" },
    { "Dominante 7",
      "Dominant 7" },
    { "Dorien",
      "Dorian" },
    { "Dossier",
      "Folder" },
    { "Dossier (trouvé automatiquement)",
      "Folder (found automatically)" },
    { "Droit",
      "Straight" },
    { "Droite (matériau corrélé)",
      "Linear (correlated material)" },
    { "Dupliquer",
      "Duplicate" },
    { "Dupliquer des clips",
      "Duplicate clips" },
    { "Dupliquer la piste sélectionnée",
      "Duplicate the selected track" },
    { "Dupliquer une piste",
      "Duplicate a track" },
    { "Durée /2",
      "Length /2" },
    { "Durée = pas de grille",
      "Length = grid step" },
    { "Durée x2",
      "Length x2" },
    { "Début de boucle à la tête",
      "Loop start at the playhead" },
    { "Décompte",
      "Count-in" },
    { "Décompte ",
      "Count-in " },
    { "Découper aux transitoires",
      "Slice at transients" },
    { "Découper aux transitoires (clips audio choisis)",
      "Slice at transients (selected audio clips)" },
    { "Découper la sélection aux transitoires (clips audio)",
      "Split the selection at transients (audio clips)" },
    { "Dégeler la piste (l'instrument reprend)",
      "Unfreeze the track (the instrument resumes)" },
    { "Dégeler une piste",
      "Unfreeze a track" },
    { "Démarrage...",
      "Starting..." },
    { "Déplacer des clips",
      "Move clips" },
    { "Déplacer des clips de piste",
      "Move clips across tracks" },
    { "Déplacer la sélection (Maj : par quatre pas) ; sans sélection, faire défiler",
      "Move the selection (Shift: by four steps); without a selection, scroll" },
    { "Déplacer les clips choisis d'un pas d'aimantation (Maj : quatre pas) ; sans sélection, faire défiler",
      "Move the selected clips by one snap step (Shift: four steps); without a selection, scroll" },
    { "Déplacer les clips choisis vers la piste voisine",
      "Move the selected clips to the neighbouring track" },
    { "Déplacer un clip",
      "Move a clip" },
    { "Déplacer un effet",
      "Move an effect" },
    { "Déplacer un effet MIDI",
      "Move a MIDI effect" },
    { "Déplacer un point d'automation",
      "Move an automation point" },
    { "Déplier (toutes les hauteurs)",
      "Unfold (all pitches)" },
    { "Déplier une piste",
      "Expand a track" },
    { "Désactiver la piste (sa machine et ses inserts sont libérés)",
      "Disable the track (its machine and inserts are released)" },
    { "Désactiver une piste",
      "Disable a track" },
    { "Déverrouiller la piste (le montage reprend)",
      "Unlock the track (editing resumes)" },
    { "Déverrouiller une piste",
      "Unlock a track" },
    { "Eff.",
      "Erase" },
    { "Effet d'un bus de départ",
      "Send bus effect" },
    { "Effets",
      "Effects" },
    { "Effets - aucune piste",
      "Effects - no track" },
    { "Effets - piste ",
      "Effects - track " },
    { "Effets MIDI (sur les notes, avant la machine)",
      "MIDI effects (on the notes, before the machine)" },
    { "Effets MIDI de la piste (",
      "MIDI effects of the track (" },
    { "Effets MIDI de la piste (%1)",
      "Track MIDI effects (%1)" },
    { "Effets — ",
      "Effects — " },
    { "Empiler les prises",
      "Stack takes" },
    { "En déplaçant",
      "When moving" },
    { "Enregistrement",
      "Recording" },
    { "Enregistrer",
      "Save" },
    { "Enregistrer (démarrer / arrêter)",
      "Record (start / stop)" },
    { "Enregistrer ce réglage comme preset, ou en charger un du même type",
      "Save this setting as a preset, or load one of the same type" },
    { "Enregistrer comme modèle de projet",
      "Save as project template" },
    { "Enregistrer comme preset...",
      "Save as preset..." },
    { "Enregistrer la piste comme preset…",
      "Save the track as a preset…" },
    { "Enregistrer la table...",
      "Save the table..." },
    { "Enregistrer le groove…",
      "Save the groove…" },
    { "Enregistrer sous",
      "Save as" },
    { "Enregistrer sous...",
      "Save as..." },
    { "Entrer dans le dossier",
      "Move into the folder" },
    { "Entrer dans le dossier du dessus",
      "Enter the folder above" },
    { "Exporter MIDI...",
      "Export MIDI..." },
    { "Exporter audio (WAV)...",
      "Export audio (WAV)..." },
    { "Exporter la piste choisie en MIDI (choisir une piste MIDI)...",
      "Export the selected track as MIDI (select a MIDI track)..." },
    { "Exporter la piste choisie en MIDI (« ",
      "Export the selected track as MIDI (« " },
    { "Exporter les stems (un WAV par piste)...",
      "Export stems (one WAV per track)..." },
    { "Extraire le groove de la piste choisie",
      "Extract the groove from the selected track" },
    { "Fantômes",
      "Ghosts" },
    { "Fenêtre unique",
      "Single window" },
    { "Fermer",
      "Close" },
    { "Fichier",
      "File" },
    { "Filtrer les pistes...",
      "Filter tracks..." },
    { "Fin de boucle à la tête",
      "Loop end at the playhead" },
    { "Fondu d'un clip",
      "Clip fade" },
    { "Forme des fondus",
      "Fade shape" },
    { "Forme des fondus croisés",
      "Crossfade shape" },
    { "Fusionner",
      "Join" },
    { "Gain du clip",
      "Clip gain" },
    { "Gain du clip (%1 dB)",
      "Clip gain (%1 dB)" },
    { "Gain du clip à 0 dB",
      "Clip gain to 0 dB" },
    { "Gamme",
      "Scale" },
    { "Geler la piste (l'instrument s'arrête)",
      "Freeze the track (the instrument stops)" },
    { "Geler une piste",
      "Freeze a track" },
    { "Gomme",
      "Eraser" },
    { "Grande (112 px)",
      "Large (112 px)" },
    { "Grille",
      "Grid" },
    { "Groupe ",
      "Group " },
    { "Groupe d'édition",
      "Edit group" },
    { "Groupe d'édition (couper et déplacer ensemble)",
      "Edit group (cut and move together)" },
    { "Hauteur",
      "Pitch" },
    { "Hauteur conservée",
      "Pitch preserved" },
    { "Hauteur conservée (WSOLA, témoin)",
      "Pitch preserved (WSOLA, reference)" },
    { "Hauteur d'une piste",
      "Track height" },
    { "Hauteur des pistes",
      "Track height" },
    { "Hauteur du clip",
      "Clip pitch" },
    { "Hauteur du clip (%1 demi-ton)",
      "Clip pitch (%1 semitone)" },
    { "Hauteur du clip (%1 demi-tons)",
      "Clip pitch (%1 semitones)" },
    { "Hauteur du clip à zéro",
      "Clip pitch to zero" },
    { "Hauteur du clip — suit la durée (mode Rééchantillonné)",
      "Clip pitch — follows the length (Resampled mode)" },
    { "Historique des modifications...",
      "Edit history..." },
    { "Humaniser",
      "Humanise" },
    { "Importer un MIDI",
      "Import a MIDI file" },
    { "Importer un MIDI dans le projet...",
      "Import a MIDI file into the project..." },
    { "Importer un fichier audio sur une piste neuve...",
      "Import an audio file onto a new track..." },
    { "Importer un projet (Ableton, FL Studio, Cubase)...",
      "Import a project (Ableton, FL Studio, Cubase)..." },
    { "Indiquer le dossier de la chaîne...",
      "Set the analysis chain folder..." },
    { "Instrument parmi les plugins trouves...",
      "Instrument from the plugins found..." },
    { "Insérer du silence",
      "Insert silence" },
    { "Insérer du silence entre les locateurs (Ctrl+Maj+I)",
      "Insert silence between the locators (Ctrl+Shift+I)" },
    { "Insérer du silence entre les locateurs (tout le morceau glisse)",
      "Insert silence between the locators (the whole song shifts)" },
    { "Insérer un accord",
      "Insert a chord" },
    { "Inverser la sélection",
      "Invert selection" },
    { "Jamais mesurée — les prises audio ne sont ",
      "Never measured — audio takes are " },
    { "Jamais mesurée — les prises audio ne sont pas compensées",
      "Never measured — audio takes are not compensated" },
    { "Joindre",
      "Join" },
    { "Joindre des clips",
      "Join clips" },
    { "Joindre les clips choisis (Ctrl+J)",
      "Join the selected clips (Ctrl+J)" },
    { "Jusqu'à la fin de la boucle (",
      "To the end of the loop (" },
    { "Jusqu'à la fin de la boucle (%1 fois)",
      "Up to the end of the loop (%1 times)" },
    { "Jusqu'à la fin de la boucle (rien n'y tient, ou pas de boucle)",
      "To the end of the loop (nothing fits, or no loop)" },
    { "L'automation suit les clips",
      "Automation follows the clips" },
    { "L'effacer",
      "Clear it" },
    { "La prendre sur la boucle",
      "Take it over the loop" },
    { "Langue",
      "Language" },
    { "Latence d'entrée",
      "Input latency" },
    { "Le clic bat",
      "The click plays" },
    { "Le clip fait N mesures",
      "Clip is N bars" },
    { "Le clip fait N mesures…",
      "The clip is N bars…" },
    { "Le morceau fait %1 mesure. Ce qu'aucun tronçon ne couvre ne sonnera pas.",
      "The song is %1 bar long. Whatever no segment covers will not sound." },
    { "Le morceau fait %1 mesures. Ce qu'aucun tronçon ne couvre ne sonnera pas.",
      "The song is %1 bars long. Whatever no segment covers will not sound." },
    { "Lecture / arrêt",
      "Play / stop" },
    { "Legato",
      "Legato" },
    { "Lente",
      "Slow" },
    { "Lente au départ",
      "Slow start" },
    { "Linéaire (deux copies du même son)",
      "Linear (two copies of the same sound)" },
    { "Liste",
      "List" },
    { "Locateurs sur la sélection",
      "Locators to the selection" },
    { "Locateurs sur la sélection (P)",
      "Locators around the selection (P)" },
    { "Locateurs sur la sélection (la boucle prend son étendue)",
      "Locators to the selection (the loop takes its extent)" },
    { "Locrien",
      "Locrian" },
    { "Lydien",
      "Lydian" },
    { "MASTER",
      "MASTER" },
    { "MONO",
      "MONO" },
    { "Machine de la piste",
      "Track machine" },
    { "Majeur",
      "Major" },
    { "Majeur 7",
      "Major 7" },
    { "Majeur 9",
      "Major 9" },
    { "Majeure",
      "Major" },
    { "Marqueur précédent",
      "Previous marker" },
    { "Marqueur suivant",
      "Next marker" },
    { "Masquer des pistes",
      "Hide tracks" },
    { "Masquer la piste (elle continue de sonner)",
      "Hide the track (it keeps sounding)" },
    { "Masquer une piste",
      "Hide a track" },
    { "Mesurer (brancher la sortie sur l'entrée)...",
      "Measure it (patch the output into the input)..." },
    { "Mesures",
      "Bars" },
    { "Mesurée : ",
      "Measured: " },
    { "Mineur",
      "Minor" },
    { "Mineur 7",
      "Minor 7" },
    { "Mineur 7 b5",
      "Minor 7 b5" },
    { "Mineur 9",
      "Minor 9" },
    { "Mineure harmonique",
      "Harmonic minor" },
    { "Mineure mélodique",
      "Melodic minor" },
    { "Mineure naturelle",
      "Natural minor" },
    { "Minutes:secondes",
      "Minutes:seconds" },
    { "Miroir des hauteurs",
      "Mirror pitches" },
    { "Mixage",
      "Mixing" },
    { "Mixer",
      "Mixer" },
    { "Mixolydien",
      "Mixolydian" },
    { "Mono-cœur",
      "Single core" },
    { "Mono-cœur (aucun thread auxiliaire)",
      "Single core (no auxiliary thread)" },
    { "Monter",
      "Move up" },
    { "Monter la piste",
      "Move the track up" },
    { "Muet",
      "Mute" },
    { "Muet (piste choisie)",
      "Mute (selected track)" },
    { "Muet sur des clips",
      "Mute clips" },
    { "Muet sur la sélection",
      "Mute the selection" },
    { "Métronome (marche / arrêt)",
      "Metronome (on / off)" },
    { "Navigateur",
      "Browser" },
    { "Navigation (non modifiable)",
      "Navigation (fixed)" },
    { "Ne plus protéger cette piste du solo des autres (Alt+clic sur Solo)",
      "Stop shielding this track from other tracks' solo (Alt+click Solo)" },
    { "Ne plus protéger du solo",
      "Remove solo safe" },
    { "Ne rien sélectionner",
      "Select nothing" },
    { "Niveau du clic",
      "Click level" },
    { "Non",
      "No" },
    { "Normale (56 px)",
      "Normal (56 px)" },
    { "Normaliser (gain = 1 / crête)",
      "Normalise (gain = 1 / peak)" },
    { "Normaliser un clip",
      "Normalise a clip" },
    { "Note :",
      "Note:" },
    { "Note douteuse précédente (Maj+D)",
      "Previous doubtful note (Shift+D)" },
    { "Note douteuse suivante (D)",
      "Next doubtful note (D)" },
    { "Note douteuse suivante (Maj : précédente)",
      "Next doubtful note (Shift: previous)" },
    { "Notes du projet... (",
      "Project notes... (" },
    { "Notes du projet... (%1 caractères)",
      "Project notes... (%1 characters)" },
    { "Notes du projet... (vides)",
      "Project notes... (empty)" },
    { "Notes plus courtes que la grille",
      "Notes shorter than the grid" },
    { "Notes plus courtes que la moitié de la grille",
      "Notes shorter than half the grid" },
    { "Notes plus faibles que 16",
      "Notes softer than 16" },
    { "Notes plus faibles que 32",
      "Notes softer than 32" },
    { "Notes plus faibles que 64",
      "Notes softer than 64" },
    { "Nouveau depuis le modèle",
      "New from template" },
    { "Nouveau dossier",
      "New folder" },
    { "Nouveau projet",
      "New project" },
    { "Ordre de jeu",
      "Play order" },
    { "Ordre de jeu... (",
      "Play order... (" },
    { "Ordre de jeu... (%1 sections)",
      "Play order... (%1 sections)" },
    { "Ordre de jeu... (aucune section)",
      "Play order... (no section)" },
    { "Oublier la mesure",
      "Forget the measurement" },
    { "Outils",
      "Tools" },
    { "Ouvrir MIDI...",
      "Open MIDI..." },
    { "Ouvrir l'interface du plugin de la piste",
      "Open the track plugin's window" },
    { "Ouvrir un projet VSM...",
      "Open a VSM project..." },
    { "Panoramique",
      "Pan" },
    { "Par tons",
      "Whole tone" },
    { "Pas de séquenceur",
      "Sequencer step" },
    { "Pas à pas",
      "Step" },
    { "Pentatonique majeure",
      "Major pentatonic" },
    { "Pentatonique mineure",
      "Minor pentatonic" },
    { "Petite (24 px)",
      "Small (24 px)" },
    { "Phase d'un clip",
      "Clip phase" },
    { "Phase inversée",
      "Phase inverted" },
    { "Phrygien",
      "Phrygian" },
    { "Piano Roll",
      "Piano Roll" },
    { "Piste",
      "Track" },
    { "Piste %1",
      "Track %1" },
    { "Piste précédente",
      "Previous track" },
    { "Piste suivante",
      "Next track" },
    { "Pistes",
      "Tracks" },
    { "Plein écran",
      "Full screen" },
    { "Plein écran (F11)",
      "Full screen (F11)" },
    { "Pli",
      "Bend" },
    { "Plier une piste",
      "Collapse a track" },
    { "Plus aucun solo (Ctrl+clic sur Solo)",
      "No solo at all (Ctrl+click Solo)" },
    { "Plus...",
      "More..." },
    { "Pointé",
      "Dotted" },
    { "Poser un point d'automation",
      "Add an automation point" },
    { "Poser un repère",
      "Add a marker" },
    { "Poser un repère ici…",
      "Add a marker here…" },
    { "Poser un échantillon",
      "Load a sample" },
    { "Post-fader (le fader l'emporte avec lui)",
      "Post-fader (the fader carries it along)" },
    { "Pression canal",
      "Channel pressure" },
    { "Pression poly",
      "Poly pressure" },
    { "Prise ",
      "Take " },
    { "Prises de « ",
      "Takes of « " },
    { "Programme",
      "Program" },
    { "Programme MIDI",
      "MIDI program" },
    { "Programme MIDI (",
      "MIDI program (" },
    { "Programme MIDI (aucun)...",
      "MIDI program (none)..." },
    { "Projet ouvert, avec des réserves",
      "Project opened, with reservations" },
    { "Projets récents",
      "Recent projects" },
    { "Protéger cette piste du solo des autres (Alt+clic sur Solo)",
      "Shield this track from other tracks' solo (Alt+click Solo)" },
    { "Protéger du solo",
      "Solo safe" },
    { "Pré-fader (le fader ne l'affecte pas)",
      "Pre-fader (the fader does not affect it)" },
    { "Pré/post-fader d'un départ",
      "Send pre/post-fader" },
    { "Préférences...",
      "Preferences..." },
    { "Prêt",
      "Ready" },
    { "Prête — trouvée dans %1",
      "Ready — found in %1" },
    { "Prête.",
      "Ready." },
    { "Publier les ",
      "Publish the " },
    { "Publier les sorties de l'instrument",
      "Publish the instrument outputs" },
    { "Publier les sorties de l'instrument ",
      "Publish the outputs of instrument " },
    { "Publier les sorties de l'instrument (cette machine n'en a qu'une)",
      "Publish the instrument's outputs (this machine has only one)" },
    { "Puissance constante (deux prises différentes)",
      "Constant power (two different takes)" },
    { "Quantifier",
      "Quantise" },
    { "Quantifier (100 %)",
      "Quantise (100%)" },
    { "Quantifier (50 %)",
      "Quantise (50%)" },
    { "Quantifier début ET fin",
      "Quantise start AND end" },
    { "Quantifier la dernière prise (grille du piano roll)",
      "Quantise the last take (piano roll grid)" },
    { "Quinte (power)",
      "Fifth (power)" },
    { "Quitter",
      "Quit" },
    { "Raccourcis clavier (%1)...",
      "Keyboard shortcuts (%1)..." },
    { "Raccourcis clavier...",
      "Keyboard shortcuts..." },
    { "Rampe descendante",
      "Ramp down" },
    { "Rampe montante",
      "Ramp up" },
    { "Ranger cette piste dans un dossier neuf",
      "Move this track into a new folder" },
    { "Rapide",
      "Fast" },
    { "Rapide au départ",
      "Fast start" },
    { "Rechercher les plugins installes...",
      "Scan for installed plugins..." },
    { "Reconstruction",
      "Reconstruction" },
    { "Reconstruction de %1",
      "Reconstruction of %1" },
    { "Reconstruire en visant la parité des pistes (le défaut de la chaîne)",
      "Reconstruct aiming for track parity (the chain's default)" },
    { "Reconstruire un morceau...",
      "Reconstruct a song..." },
    { "Redimensionner un clip",
      "Resize a clip" },
    { "Remettre tous les effets",
      "Enable all effects" },
    { "Remettre un effet",
      "Enable an effect" },
    { "Remplacer",
      "Replace" },
    { "Rendre muet",
      "Mute" },
    { "Rendre muet / audible",
      "Mute / unmute" },
    { "Rendu muet par son dossier",
      "Muted by its folder" },
    { "Renommer ce repère…",
      "Rename this marker…" },
    { "Renommer la piste",
      "Rename the track" },
    { "Renommer les pistes en série",
      "Rename tracks in series" },
    { "Renommer les pistes en série (",
      "Rename tracks in series (" },
    { "Renommer les pistes en série (%1 visibles)...",
      "Rename tracks in series (%1 visible)..." },
    { "Renommer un clip",
      "Rename a clip" },
    { "Renommer un repère",
      "Rename a marker" },
    { "Renommer…",
      "Rename…" },
    { "Replier",
      "Collapse" },
    { "Replier le dossier",
      "Collapse the folder" },
    { "Replier sur les hauteurs jouées",
      "Fold to the played pitches" },
    { "Replier sur les hauteurs jouées (aucune note)",
      "Fold to the played pitches (no notes)" },
    { "Reporter la piste en audio (définitif)",
      "Bounce the track to audio (permanent)" },
    { "Reporter la sélection en audio",
      "Bounce the selection to audio" },
    { "Reporter la sélection en audio (sur une piste neuve)",
      "Bounce the selection to audio (onto a new track)" },
    { "Reporter les effets MIDI dans les notes",
      "Bake the MIDI effects into the notes" },
    { "Reporter les effets MIDI dans les notes (définitif)",
      "Bounce the MIDI effects into the notes (permanent)" },
    { "Reporter une piste en audio",
      "Bounce a track to audio" },
    { "Resserrer les nuances de moitié",
      "Compress the dynamics by half" },
    { "Retirer",
      "Remove" },
    { "Retirer ce bus",
      "Remove this bus" },
    { "Retirer ce marqueur",
      "Remove this warp marker" },
    { "Retirer ce repère",
      "Remove this marker" },
    { "Retirer le changement de cette mesure",
      "Remove the change at this bar" },
    { "Retirer le changement de cette mesure (aucun ici)",
      "Remove the change at this bar (none here)" },
    { "Retirer les chevauchements",
      "Remove overlaps" },
    { "Retirer les effets MIDI",
      "Remove the MIDI effects" },
    { "Retirer tous les effets MIDI",
      "Remove all MIDI effects" },
    { "Retirer un bus de départ",
      "Remove a send bus" },
    { "Retirer un changement de signature",
      "Remove a time signature change" },
    { "Retirer un effet",
      "Remove an effect" },
    { "Retirer un effet MIDI",
      "Remove a MIDI effect" },
    { "Retirer un marqueur de tempo",
      "Remove a warp marker" },
    { "Retirer un point d'automation",
      "Remove an automation point" },
    { "Retirer un repère",
      "Remove a marker" },
    { "Retirer un événement",
      "Remove an event" },
    { "Retirer une prise",
      "Remove a take" },
    { "Retirer une prise du tiroir",
      "Remove a take from the drawer" },
    { "Retour au début",
      "Return to the start" },
    { "Retour audible",
      "Audible return" },
    { "Retour d'un départ",
      "Send return" },
    { "Revenir au point de départ",
      "Return to the starting point" },
    { "Rogner au son",
      "Trim to sound" },
    { "Rogner au son (détecter le silence)",
      "Trim to sound (detect silence)" },
    { "Règle",
      "Ruler" },
    { "Réactiver",
      "Unmute" },
    { "Réactiver la piste (sa machine revient)",
      "Re-enable the track (its machine comes back)" },
    { "Réactiver une piste",
      "Re-enable a track" },
    { "Récupérer ce qui vient d'être joué",
      "Recover what was just played" },
    { "Récupérer ce qui vient d'être joué (",
      "Recover what was just played (" },
    { "Récupérer ce qui vient d'être joué (%1 événements)",
      "Recover what was just played (%1 events)" },
    { "Récupérer ce qui vient d'être joué (rien en mémoire)",
      "Recover what was just played (nothing in memory)" },
    { "Réduire les points d'automation",
      "Thin the automation points" },
    { "Réduire les points d'automation (",
      "Thin automation points (" },
    { "Réduire les points d'automation (%1 points)",
      "Thin the automation points (%1 points)" },
    { "Région de punch",
      "Punch region" },
    { "Région de punch (Alt sur la règle)",
      "Punch region (Alt on the ruler)" },
    { "Réglage d'effet",
      "Effect setting" },
    { "Réglage d'effet MIDI",
      "MIDI effect setting" },
    { "Réglages audio...",
      "Audio settings..." },
    { "Réordonner les pistes",
      "Reorder tracks" },
    { "Répéter des clips",
      "Repeat clips" },
    { "Répéter la sélection",
      "Repeat the selection" },
    { "Répéter la sélection (à la suite)",
      "Repeat the selection (end to end)" },
    { "Rétablir",
      "Redo" },
    { "Rétablir %1",
      "Restore %1" },
    { "Rétablir : ",
      "Redo: " },
    { "Rétrograder",
      "Reverse" },
    { "Rééchantillonné",
      "Resampled" },
    { "SANS SON",
      "NO SOUND" },
    { "Sections (déduites des repères)",
      "Sections (derived from the markers)" },
    { "Seulement au décompte",
      "Only during the count-in" },
    { "Seulement à l'enregistrement",
      "Only while recording" },
    { "Signature %1",
      "Time signature %1" },
    { "Signature à la tête de lecture",
      "Time signature at the playhead" },
    { "Sinus (une période par mesure)",
      "Sine (one cycle per bar)" },
    { "Solo",
      "Solo" },
    { "Solo (piste choisie)",
      "Solo (selected track)" },
    { "Solo exclusif",
      "Exclusive solo" },
    { "Solo exclusif de la piste choisie (Ctrl+clic sur Solo)",
      "Exclusive solo of the selected track (Ctrl+click Solo)" },
    { "Sortie MIDI",
      "MIDI output" },
    { "Sortie MIDI matérielle",
      "Hardware MIDI output" },
    { "Sortie MIDI matérielle (→ ",
      "Hardware MIDI output (→ " },
    { "Sortie de la piste",
      "Track output" },
    { "Sortir du dossier",
      "Leave the folder" },
    { "Statistiques du projet...",
      "Project statistics..." },
    { "Suivre",
      "Follow" },
    { "Suivre le tempo",
      "Follow tempo" },
    { "Superposer",
      "Overlay" },
    { "Supprimer",
      "Delete" },
    { "Supprimer des clips",
      "Delete clips" },
    { "Supprimer des pistes",
      "Delete tracks" },
    { "Supprimer la piste sélectionnée",
      "Delete the selected track" },
    { "Supprimer la sélection",
      "Delete the selection" },
    { "Supprimer le temps entre les locateurs (Ctrl+Maj+K)",
      "Delete time between the locators (Ctrl+Shift+K)" },
    { "Supprimer le temps entre les locateurs (tout le morceau glisse)",
      "Delete the time between the locators (the whole song shifts)" },
    { "Supprimer une piste",
      "Delete a track" },
    { "Supprimer une plage de temps",
      "Delete a time range" },
    { "Swing",
      "Swing" },
    { "Synth Rack",
      "Synth Rack" },
    { "Sél.",
      "Sel." },
    { "Sélection",
      "Selection" },
    { "Taille de l'interface",
      "Interface size" },
    { "Tempo",
      "Tempo" },
    { "Temps et durée",
      "Time and length" },
    { "Threads de rendu",
      "Render threads" },
    { "Tournez un potentiomètre pour %1...",
      "Turn a knob for %1..." },
    { "Tous les canaux",
      "All channels" },
    { "Tout",
      "Fit" },
    { "Tout désélectionner",
      "Select none" },
    { "Tout effacer",
      "Clear all" },
    { "Tout remettre",
      "Enable all" },
    { "Tout rétablir",
      "Restore all" },
    { "Tout sélectionner",
      "Select all" },
    { "Tout sélectionner dans l'arrangement (Ctrl+A)",
      "Select all in the arrangement (Ctrl+A)" },
    { "Toutes les notes de même hauteur",
      "All notes of the same pitch" },
    { "Toutes les notes douteuses",
      "All doubtful notes" },
    { "Toutes les pistes à la fenêtre (arrangement)",
      "Fit all tracks to the window (arrangement)" },
    { "Transcrire en MIDI (Basic Pitch, Python)",
      "Transcribe to MIDI (Basic Pitch, Python)" },
    { "Transcrire le clip audio choisi en MIDI (",
      "Transcribe the selected audio clip to MIDI (" },
    { "Transcrire le clip audio choisi en MIDI (Basic Pitch)",
      "Transcribe the selected audio clip to MIDI (Basic Pitch)" },
    { "Transcrire un clip en MIDI",
      "Transcribe a clip to MIDI" },
    { "Transport",
      "Transport" },
    { "Transposer +1 demi-ton",
      "Transpose +1 semitone" },
    { "Transposer -1 demi-ton",
      "Transpose -1 semitone" },
    { "Transposer d'un demi-ton (Maj : d'une octave) ; sans sélection, faire défiler",
      "Transpose by a semitone (Shift: by an octave); without a selection, scroll" },
    { "Triangle (une période par mesure)",
      "Triangle (one cycle per bar)" },
    { "Trim ",
      "Trim " },
    { "Trim d'entrée",
      "Input trim" },
    { "Triolet",
      "Triplet" },
    { "Tronçons — « de telle mesure à telle mesure, telle prise »",
      "Segments — “from this bar to that bar, this take”" },
    { "Tête : mesure précédente",
      "Playhead: previous bar" },
    { "Tête : mesure suivante",
      "Playhead: next bar" },
    { "Tête : temps précédent",
      "Playhead: previous beat" },
    { "Tête : temps suivant",
      "Playhead: next beat" },
    { "Tête au début de la sélection",
      "Playhead to the start of the selection" },
    { "Un clic sur un pas y revient. Le pas en surbrillance est l'état courant ; au-dessous, ce que Rétablir rendrait.",
      "A click on a step returns to it. The highlighted step is the current state; below it, what Redo would restore." },
    { "Un plugin (.clap / .vst3)...",
      "A plugin (.clap / .vst3)..." },
    { "Verrouiller la piste (le montage s'arrête)",
      "Lock the track (editing stops)" },
    { "Verrouiller une piste",
      "Lock a track" },
    { "Voir le dernier rapport d'import",
      "Show the last import report" },
    { "Voir le rapport de reconstruction",
      "Show the reconstruction report" },
    { "Volume",
      "Volume" },
    { "Vél.",
      "Vel." },
    { "Vélocité",
      "Velocity" },
    { "Vélocité +10 %",
      "Velocity +10%" },
    { "Vélocité -10 %",
      "Velocity -10%" },
    { "Vélocité 127",
      "Velocity 127" },
    { "Vélocité 64",
      "Velocity 64" },
    { "W latch",
      "W latch" },
    { "W touch",
      "W touch" },
    { "Zoom : la sélection",
      "Zoom: the selection" },
    { "Zoom : sur la sélection",
      "Zoom: to the selection" },
    { "Zoom : tout voir",
      "Zoom: show all" },
    { "Zoom arrière",
      "Zoom out" },
    { "Zoom avant",
      "Zoom in" },
    { "bus de groupe",
      "group bus" },
    { "choisir un effet",
      "choose an effect" },
    { "de la mesure",
      "from bar" },
    { "devient une prise)",
      "becomes a take)" },
    { "dossier (ne joue rien)",
      "folder (plays nothing)" },
    { "mes. ",
      "bar " },
    { "mesures %1 à %2   →   %3",
      "bars %1 to %2   →   %3" },
    { "pas compensées",
      "not compensated" },
    { "project.json",
      "project.json" },
    { "reconstruireEnParite",
      "reconstruireEnParite" },
    { "À l'arrêt",
      "On stop" },
    { "À l'envers",
      "Reversed" },
    { "À propos de Vintage Synth MIDI Studio",
      "About Vintage Synth MIDI Studio" },
    { "Éclater par hauteur",
      "Explode by pitch" },
    { "Éclater par hauteur (",
      "Split by pitch (" },
    { "Éclater par hauteur (une seule hauteur ici)",
      "Split by pitch (only one pitch here)" },
    { "Écoute : les deux",
      "Monitoring: both" },
    { "Écoute : original",
      "Monitoring: original" },
    { "Écoute : reconstruction",
      "Monitoring: reconstruction" },
    { "Écoute A/B : pas d'original",
      "A/B monitoring: no original" },
    { "Écoute automatique (une piste audio armée, transport arrêté ou en enregistrement)",
      "Automatic monitoring (one audio track armed, transport stopped or recording)" },
    { "Écoute de l'entrée",
      "Input monitoring" },
    { "Écoute en mono (jamais dans un export)",
      "Mono monitoring (never in an export)" },
    { "Écoute manuelle (l'interrupteur ci-dessus)",
      "Manual monitoring (the switch above)" },
    { "Écoute quand une piste est armée (une piste audio armée, toujours)",
      "Monitoring while a track is armed (one audio track armed, always)" },
    { "Écouter l'entrée en direct (latence du périphérique)",
      "Monitor the input live (device latency)" },
    { "Édition",
      "Edit" },
    { "Égale puissance (matériau décorrélé)",
      "Equal power (decorrelated material)" },
    { "Égaliser les nuances (toutes à la moyenne)",
      "Even out the dynamics (all to the average)" },
    { "Étape %1 sur %2 — %3",
      "Step %1 of %2 — %3" },
    { "Étendre le choix vers le bas",
      "Extend the selection down" },
    { "Étendre le choix vers le haut",
      "Extend the selection up" },
    { "Étirer un clip",
      "Stretch a clip" },
    { "à",
      "to" },
    { "► état courant",
      "► current state" },
};

constexpr int kNombreDePaires = static_cast<int>(sizeof(kAnglais) / sizeof(kAnglais[0]));

Langue::Choix& etatCourant() {
    static Langue::Choix courant = Langue::Choix::Francais;
    return courant;
}

const char* kCleReglage = "langueInterface";

Langue::Choix depuisLeTexte(const juce::String& texte, Langue::Choix defaut) {
    const juce::String t = texte.trim().toLowerCase();
    if (t == "en" || t == "anglais" || t == "english") return Langue::Choix::Anglais;
    if (t == "fr" || t == "francais" || t == juce::String::fromUTF8("français")) return Langue::Choix::Francais;
    return defaut;
}

/// Installe (ou retire) la table de JUCE. Le français ne pose AUCUNE table :
/// `juce::translate` rend alors son argument, ce qui est exactement le
/// comportement voulu et ne coûte pas une recherche.
void poserLaTable(Langue::Choix choix) {
    if (choix == Langue::Choix::Francais) {
        juce::LocalisedStrings::setCurrentMappings(nullptr);
        return;
    }
    juce::String texte;
    texte << "language: English\n" << "countries: gb us\n\n";
    for (const auto& paire : kAnglais) {
        // LE FORMAT DE JUCE, ET SON SEUL PIÈGE : la clé et la valeur sont des
        // littéraux entre guillemets sur une ligne, et un guillemet ou un
        // retour à la ligne DANS le texte doit être échappé -- sans quoi la
        // ligne se coupe en silence et la traduction disparaît sans erreur.
        auto echappe = [](const char* brut) {
            return juce::String::fromUTF8(brut).replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n");
        };
        texte << "\"" << echappe(paire.fr) << "\" = \"" << echappe(paire.en) << "\"\n";
    }
    juce::LocalisedStrings::setCurrentMappings(new juce::LocalisedStrings(texte, false));
}

} // namespace

Langue::Choix Langue::courante() { return etatCourant(); }

int Langue::tailleDeLaTable() { return kNombreDePaires; }

juce::String Langue::libelle(Choix choix) {
    // CHAQUE LANGUE DANS LA SIENNE : c'est la convention de tous les sélecteurs
    // de langue, et la seule qui permette à quelqu'un de retrouver la sienne
    // quand l'interface est posée dans une langue qu'il ne lit pas.
    return choix == Choix::Anglais ? juce::String("English")
                                   : juce::String::fromUTF8("Français");
}

bool Langue::appliquer(Choix choix) {
    const bool change = choix != etatCourant();
    etatCourant() = choix;
    poserLaTable(choix);
    UiScale::properties().setValue(kCleReglage, choix == Choix::Anglais ? "en" : "fr");
    UiScale::properties().saveIfNeeded();
    return change;
}

void Langue::appliquerAuDemarrage() {
    Choix choix = depuisLeTexte(UiScale::properties().getValue(kCleReglage, "fr"),
                                Choix::Francais);
    // VSM_LANGUE L'EMPORTE, SANS ÉCRASER LE RÉGLAGE. Un banc choisit sa langue
    // pour une course ; il ne doit pas changer ce que l'utilisateur a réglé,
    // sans quoi une vérification en anglais laisserait le DAW en anglais.
    if (const char* force = std::getenv("VSM_LANGUE"); force != nullptr && *force) {
        etatCourant() = depuisLeTexte(juce::String::fromUTF8(force), choix);
        poserLaTable(etatCourant());
        return;
    }
    etatCourant() = choix;
    poserLaTable(choix);
}

juce::String tr(const char* texte) {
    // `fromUTF8` ET NON `juce::String(const char*)` : le second lit les octets
    // en Latin-1 et rend « s'éclaircit » en « s'Â©claircit ». Passer par la
    // traduction devient donc aussi la façon sûre d'écrire un accent.
    return juce::translate(juce::String::fromUTF8(texte));
}

juce::String tr(const char8_t* texte) {
    return juce::translate(juce::String::fromUTF8(reinterpret_cast<const char*>(texte)));
}

juce::String tr(const juce::String& texte) { return juce::translate(texte); }

juce::String trGeste(const juce::String& libelle) {
    const juce::String signature = juce::String::fromUTF8(u8"Signature ");
    if (libelle.startsWith(signature))
        return tr(u8"Signature %1").replace("%1", libelle.substring(signature.length()));
    return tr(libelle);
}

} // namespace vsm::app::ui
